In [1]:
import pandas as pd 
from sklearn.datasets import load_digits
digits=load_digits()

C:\Users\pinto\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
digits.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [5]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
df=pd.DataFrame(digits.data,digits.target)
df

0    1     2     3     4     5    6    7    8    9   ...   54   55   56  \
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0  0.0   
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0  0.0   

     57   58    59    60    61   62   63  
0   0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1   0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2   0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3   0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4   0.0  0.0   2.0  16.0   4.0  0.0  0.0  
..  ...  ...   ...   ...   ...  ...  ...  
9   0.0  2.0  14.0  15.0   9.0  0.0  0.0  
0   0.0  6.0  16.0  14.0   6.0  0.0  0.0  
8   0.0  2.0   9.0  13.0   6.0  0.0  0.0  
9   0.0  5.0  12.0  16.0  12.0  0.0  0.0  
8   1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [11]:
df['target']=digits.target

In [12]:
df

0    1     2     3     4     5    6    7    8    9  ...   55   56   57  \
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  1.0   

     58    59    60    61   62   63  target  
0   6.0  13.0  10.0   0.0  0.0  0.0       0  
1   0.0  11.0  16.0  10.0  0.0  0.0       1  
2   0.0   3.0  11.0  16.0  9.0  0.0       2  
3   7.0  13.0  13.0   9.0  0.0  0.0       3  
4   0.0   2.0  16.0   4.0  0.0  0.0       4  
..  ...   ...   ...   ...  ...  ...     ...  
9   2.0  14.0  15.0   9.0  0.0  0.0       9  
0   6.0  16.0  14.0   6.0  0.0  0.0       0  
8   2.0   9.0  13.0   6.0  0.0  0.0       8  
9   5.0  12.0  16.0  12.0  0.0  0.0       9  
8   8.0  12.0  14.0  12.0  1.0  0.0       8  

[1797 rows x 65 columns]

In [14]:
x=df.drop('target',axis='columns')
x

0    1     2     3     4     5    6    7    8    9   ...   54   55   56  \
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0  0.0   
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0  0.0   

     57   58    59    60    61   62   63  
0   0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1   0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2   0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3   0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4   0.0  0.0   2.0  16.0   4.0  0.0  0.0  
..  ...  ...   ...   ...   ...  ...  ...  
9   0.0  2.0  14.0  15.0   9.0  0.0  0.0  
0   0.0  6.0  16.0  14.0   6.0  0.0  0.0  
8   0.0  2.0   9.0  13.0   6.0  0.0  0.0  
9   0.0  5.0  12.0  16.0  12.0  0.0  0.0  
8   1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [15]:
y=df.target
y

0    0
1    1
2    2
3    3
4    4
    ..
9    9
0    0
8    8
9    9
8    8
Name: target, Length: 1797, dtype: int32

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.8)

In [18]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
model.score(x_test,y_test)

0.9944444444444445

In [28]:
model_c=SVC(C=.1)
model_c.fit(x_train,y_train)
model_c.score(x_test,y_test)

0.9611111111111111

In [33]:
model_g=SVC(gamma='auto')
model_g.fit(x_train,y_train)
model_g.score(x_test,y_test)

0.5583333333333333

In [34]:
model_g=SVC(kernel='linear')
model_g.fit(x_train,y_train)
model_g.score(x_test,y_test)

0.9777777777777777

In [35]:
model_g=SVC(kernel='rbf')
model_g.fit(x_train,y_train)
model_g.score(x_test,y_test)

0.9944444444444445