In [2]:
import numpy as np
import pandas as pd 
from sklearn import linear_model

In [3]:
df=pd.read_csv(r"F:\WORK\Machine Learning\Multivariate Regession\homeprices.csv")

In [4]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
new_df=df.drop('price',axis='columns')
new_df
model=linear_model.LinearRegression()

In [14]:
new_df

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [15]:
model.fit(new_df,df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
model.predict([[4000,5,20]])

array([721882.81185098])

In [20]:
import pickle

In [26]:
with open("F:\WORK\Machine Learning\Save & Load model using pickle, sklearn joblib\model_pickel",'wb') as file:
    pickle.dump(model,file)

In [27]:
with open("F:\WORK\Machine Learning\Save & Load model using pickle, sklearn joblib\model_pickel",'rb') as file:
    mp=pickle.load(file)

In [28]:
mp.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [29]:
mp.predict([[4000,5,20]])

array([721882.81185098])

In [30]:
from sklearn.externals import joblib

C:\Users\pinto\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [32]:
joblib.dump(model,"F:\WORK\Machine Learning\Save & Load model using pickle, sklearn joblib\model_joblib")

['F:\\WORK\\Machine Learning\\Save & Load model using pickle, sklearn joblib\\model_joblib']

In [33]:
mj=joblib.load("F:\WORK\Machine Learning\Save & Load model using pickle, sklearn joblib\model_joblib")

In [34]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [36]:
mj.predict([[4000,5,20]])

array([721882.81185098])